hl.on("hyprland.start", function()
	hl.exec_cmd("quickshell")
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("1password --silent")
	hl.exec_cmd("dunst")
	hl.exec_cmd("~/.local/bin/mount-nas.sh")
	hl.exec_cmd("flatpak run net.sonuscape.mouseless")
end)
