hl.on("hyprland.start", function()
	hl.exec_cmd("quickshell")
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("1password --silent")
	hl.exec_cmd("dunst")
	hl.exec_cmd("~/.local/bin/mount-nas.sh")
	hl.exec_cmd("~/.local/bin/Mouseless_v1.0.0-preview.3_arch-20260510.0.525573_x86_64.AppImage")
end)
