# fixed issue i was having with hyprshot region screenshots ending up with a 1px border
# https://www.reddit.com/r/hyprland/comments/1eu3qdv/comment/lijb45m/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
layerrule = no_anim on, match:namespace hyprpicker
layerrule = no_anim on, match:namespace selection
